### ISSUE TITLE
Heatmap rows are not displayed properly (JIRA bug VRS-15966)

### ISSUE THREAD

**Issue by psjawale** [nuagenetworks/visualization-framework#721] opened 2018-08-17 22:18 UTC
Please check attached image
![heatmap rows](https://user-images.githubusercontent.com/15370884/44291056-c27e7f00-a230-11e8-8069-fa22db1598bf.PNG)

**Comment by nxanil** [comment] 2018-10-03 15:37
@bmukheja @natabal 

I think we have fixed that issue and not able to reproduce now.
Please have a look and let me know.

**Comment by psjawale** [comment] 2018-10-03 20:18
@nxanil To reproduce the issue, scroll back to the point in history where there is no data available and then back again to the point where we have data.  Forced page refresh fixes the nonalignment of the rows.
(heatmap scroll issue #720 fix looks good and working fine)

**Comment by nxanil** [comment] 2018-10-04 07:19
@psjawale 

Fixed in [PR](https://github.com/nuagenetworks/vis-graphs/pull/37). Please have a look.

**Closed** 2018-10-18 16:12 UTC
Labels: aar-ike
